### PR TITLE
Removed bands selectors with no options (created new branch for bands commit)

### PR DESCRIPTION
**Pull request by DarkManiel**
Could not test with multiple layers since we lack the ability to ingest time-series data. May need to test further on more layers once able to ingest more layers.

### CODE REVIEW

**Comment by ZachSand** [comment]
Did you mean to commit the changes to?
ingest-spatial.sh, run-server.sh

and add?
stop_everything.sh, start_everything.sh, update_+_run.sh, (3) .DS_Store binary files

**Comment by DarkManiel** [comment]
No, how do I only include certain files in a pull request? I only really want to include the viewer code for this.

**Comment by ZachSand** [comment]
If I understand the strategy we're using -- you need to keep a clean (updated) fork of the geotrellis/gt-admin. For each change (that will eventually become a PR) you need to make a branch. When you're making your changes make sure you checkout that branch and only "git add/git commit" those files that you want in the PR to that branch. Then when you submit a pull request it will only pick up those changes.

**Comment by DarkManiel** [comment]
Okay, I see. Thanks. I thought this was a bit messy, but wasn't sure how we were supposed to do it. I'll redo these submissions then.

**Comment by ZachSand** [comment]
If you add a new commit you your branch, reverting back all the files you don't want in the PR, and then push that commit, I think it should fix this PR. 
http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review

**Pull request closed without merging**
